// Code generated by protoc-gen-go.
// source: crawler.proto
// DO NOT EDIT!

package soso_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SosoCrawler struct {
	Query            *string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Engine           *string `protobuf:"bytes,2,opt,name=engine" json:"engine,omitempty"`
	Url              *string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Ua               *string `protobuf:"bytes,4,opt,name=ua" json:"ua,omitempty"`
	Sleeptime        *string `protobuf:"bytes,5,opt,name=sleeptime" json:"sleeptime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SosoCrawler) Reset()         { *m = SosoCrawler{} }
func (m *SosoCrawler) String() string { return proto.CompactTextString(m) }
func (*SosoCrawler) ProtoMessage()    {}

func (m *SosoCrawler) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *SosoCrawler) GetEngine() string {
	if m != nil && m.Engine != nil {
		return *m.Engine
	}
	return ""
}

func (m *SosoCrawler) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *SosoCrawler) GetUa() string {
	if m != nil && m.Ua != nil {
		return *m.Ua
	}
	return ""
}

func (m *SosoCrawler) GetSleeptime() string {
	if m != nil && m.Sleeptime != nil {
		return *m.Sleeptime
	}
	return ""
}

func init() {
}
