// Code generated by protoc-gen-go.
// source: yuanso.proto
// DO NOT EDIT!

package soso_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SogouMetaSend struct {
	Query            *string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Engine           *string `protobuf:"bytes,2,opt,name=engine" json:"engine,omitempty"`
	Html             *string `protobuf:"bytes,3,opt,name=html" json:"html,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SogouMetaSend) Reset()         { *m = SogouMetaSend{} }
func (m *SogouMetaSend) String() string { return proto.CompactTextString(m) }
func (*SogouMetaSend) ProtoMessage()    {}

func (m *SogouMetaSend) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *SogouMetaSend) GetEngine() string {
	if m != nil && m.Engine != nil {
		return *m.Engine
	}
	return ""
}

func (m *SogouMetaSend) GetHtml() string {
	if m != nil && m.Html != nil {
		return *m.Html
	}
	return ""
}

type SogouMetaResp struct {
	Status           *int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Content          *string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SogouMetaResp) Reset()         { *m = SogouMetaResp{} }
func (m *SogouMetaResp) String() string { return proto.CompactTextString(m) }
func (*SogouMetaResp) ProtoMessage()    {}

func (m *SogouMetaResp) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *SogouMetaResp) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func init() {
}
